services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGODB_HOST=mongodb

networks:
  app-network:
    driver: bridge