services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge